// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectShopping.DbContexts;

namespace ProjectShopping.Migrations
{
    [DbContext(typeof(ShopingDbContext))]
    [Migration("20210424171723_test2")]
    partial class test2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectShopping.Entities.Product", b =>
                {
                    b.Property<Guid>("PID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("PID");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            PID = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Description = "aasdf as dfgaskjdf askdfh askjdfh lasdf",
                            Gender = "Men",
                            MainCategory = "Shirt",
                            Name = "abcd",
                            Price = 20
                        });
                });

            modelBuilder.Entity("ProjectShopping.Entities.Stock", b =>
                {
                    b.Property<Guid>("PID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("color")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("size")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("PID", "color", "size");

                    b.ToTable("Stock");
                });

            modelBuilder.Entity("ProjectShopping.Entities.Tags", b =>
                {
                    b.Property<Guid>("PID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tag")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PID", "tag");

                    b.ToTable("AllTags");

                    b.HasData(
                        new
                        {
                            PID = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            tag = "cotton"
                        },
                        new
                        {
                            PID = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            tag = "Full-sleves"
                        });
                });

            modelBuilder.Entity("ProjectShopping.Entities.Tags", b =>
                {
                    b.HasOne("ProjectShopping.Entities.Product", "product")
                        .WithMany("TagList")
                        .HasForeignKey("PID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("ProjectShopping.Entities.Product", b =>
                {
                    b.Navigation("TagList");
                });
#pragma warning restore 612, 618
        }
    }
}
