// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectShopping.DbContexts;

namespace ProjectShopping.Migrations
{
    [DbContext(typeof(ShopingDbContext))]
    [Migration("20210424105247_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectShopping.Entities.Product", b =>
                {
                    b.Property<Guid>("PID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("PID");

                    b.ToTable("products");
                });

            modelBuilder.Entity("ProjectShopping.Entities.Tags", b =>
                {
                    b.Property<Guid>("PID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tag")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PID", "tag");

                    b.ToTable("AllTags");
                });

            modelBuilder.Entity("ProjectShopping.Entities.Tags", b =>
                {
                    b.HasOne("ProjectShopping.Entities.Product", "product")
                        .WithMany("taglist")
                        .HasForeignKey("PID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("ProjectShopping.Entities.Product", b =>
                {
                    b.Navigation("taglist");
                });
#pragma warning restore 612, 618
        }
    }
}
